/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gpaudra.gstorecustomer.view;

import com.gpaudra.gstorecustomer.controller.PelangganJpaController;
import com.gpaudra.gstorecustomer.controller.exceptions.NonexistentEntityException;
import com.gpaudra.gstorecustomer.model.Pelanggan;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author Gesang Paudra Jaya
 */
public class customer_form extends javax.swing.JFrame {
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("customerPU");
    Pelanggan pelanggan = new Pelanggan();
    PelangganJpaController pelangganctrl = new PelangganJpaController(emf);
    /**
     * Creates new form customer_form
     */
    public customer_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        inputAlamat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputNotelp = new javax.swing.JTextField();
        SimpanData = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CariData = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        UpdateData = new javax.swing.JButton();
        inputKode = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        HapusData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(28, 28, 28));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM PELANGGAN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Full Name");

        inputNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputNamaKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Username");

        inputUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputUsernameKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Email");

        inputEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputEmailKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Alamat");

        inputAlamat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputAlamatKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Telephone");

        inputNotelp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputNotelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputNotelpKeyPressed(evt);
            }
        });

        SimpanData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SimpanData.setText("SIMPAN");
        SimpanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanDataActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("©Gesang Paudra Jaya_2020");

        CariData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CariData.setText("CARI");
        CariData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariDataActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("ID Pelanggan*");

        UpdateData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UpdateData.setText("PERBARUI");
        UpdateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDataActionPerformed(evt);
            }
        });

        inputKode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("*ID hanya diisi saat pencarian dan pembaruan data");

        HapusData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        HapusData.setText("HAPUS");
        HapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(99, 99, 99)
                                    .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(SimpanData)
                                            .addGap(108, 108, 108)
                                            .addComponent(UpdateData)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(HapusData))
                                        .addComponent(inputNotelp, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputKode)
                                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addComponent(CariData, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CariData)
                    .addComponent(inputKode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputNotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SimpanData)
                    .addComponent(UpdateData)
                    .addComponent(HapusData))
                .addGap(43, 43, 43)
                .addComponent(jLabel9)
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimpanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanDataActionPerformed
        
        pelanggan.setUsername(inputUsername.getText());
        pelanggan.setNmPelanggan(inputNama.getText());
        pelanggan.setEmailPelanggan(inputEmail.getText());
        pelanggan.setAlmtPelanggan(inputAlamat.getText());
        pelanggan.setNotelpPelanggan(inputNotelp.getText());
        
        pelangganctrl.create(pelanggan);
        JOptionPane.showMessageDialog(null, "Data Pelanggan Tersimpan");
            inputNama.setText("");
            inputUsername.setText("");
            inputEmail.setText("");
            inputAlamat.setText("");
            inputNotelp.setText("");
        
    }//GEN-LAST:event_SimpanDataActionPerformed

    private void inputNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNamaKeyPressed
        int kunci = evt.getKeyCode();
        if(kunci==10){
            inputUsername.requestFocus();
        }
    }//GEN-LAST:event_inputNamaKeyPressed

    private void inputUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputUsernameKeyPressed
        int kunci = evt.getKeyCode();
        if(kunci==10){
            inputEmail.requestFocus();
        }
    }//GEN-LAST:event_inputUsernameKeyPressed

    private void inputEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputEmailKeyPressed
        int kunci = evt.getKeyCode();
        if(kunci==10){
            inputAlamat.requestFocus();
        }
    }//GEN-LAST:event_inputEmailKeyPressed

    private void inputAlamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputAlamatKeyPressed
        int kunci = evt.getKeyCode();
        if(kunci==10){
            inputNotelp.requestFocus();
        }
    }//GEN-LAST:event_inputAlamatKeyPressed

    private void inputNotelpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNotelpKeyPressed
        int kunci = evt.getKeyCode();
        if(kunci==10){
            SimpanData.requestFocus();
        }
    }//GEN-LAST:event_inputNotelpKeyPressed

    private void CariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariDataActionPerformed
        String hasil2 = inputKode.getText();
        int hasil = Integer.parseInt(hasil2);
        
        pelanggan = pelangganctrl.findPelanggan(hasil);
        
        
        inputNama.setText(pelanggan.getNmPelanggan());
        inputUsername.setText(pelanggan.getUsername());
        inputEmail.setText(pelanggan.getEmailPelanggan());
        inputAlamat.setText(pelanggan.getAlmtPelanggan());
        inputNotelp.setText(pelanggan.getNotelpPelanggan());
        
        
    }//GEN-LAST:event_CariDataActionPerformed

    private void UpdateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDataActionPerformed
        String hasil2 = inputKode.getText();
        int hasil = Integer.parseInt(hasil2);
        
        pelanggan = pelangganctrl.findPelanggan(hasil);
        
        pelanggan.setNmPelanggan(inputNama.getText());
        pelanggan.setUsername(inputUsername.getText());
        pelanggan.setEmailPelanggan(inputEmail.getText());
        pelanggan.setAlmtPelanggan(inputAlamat.getText());
        pelanggan.setNotelpPelanggan(inputNotelp.getText());
        
        try {
            pelangganctrl.edit(pelanggan);
            JOptionPane.showMessageDialog(null, "Data Pelanggan Diperbaharui");
            inputKode.setText("");
            inputNama.setText("");
            inputUsername.setText("");
            inputEmail.setText("");
            inputAlamat.setText("");
            inputNotelp.setText("");
            
        } catch (Exception ex) {
            Logger.getLogger(customer_form.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_UpdateDataActionPerformed

    private void HapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusDataActionPerformed
        int pilihan = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus data ini?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        
        if(pilihan==0){
            String hasil2 = inputKode.getText();
            int hasil = Integer.parseInt(hasil2);
            
            try {
                pelangganctrl.destroy(hasil);
                JOptionPane.showMessageDialog(null, "Data Pelanggan telah Dihapus");
                inputKode.setText("");
                inputNama.setText("");
                inputUsername.setText("");
                inputEmail.setText("");
                inputAlamat.setText("");
                inputNotelp.setText("");
                
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(customer_form.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
    }//GEN-LAST:event_HapusDataActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CariData;
    private javax.swing.JButton HapusData;
    private javax.swing.JButton SimpanData;
    private javax.swing.JButton UpdateData;
    private javax.swing.JTextField inputAlamat;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputKode;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputNotelp;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
